import './lab.css';

const labName='Digital Twin Research Center for Infrastructure Assets';
document.title=`DTIA — ${labName}`;
document.querySelector('meta[name="theme-color"]').content='#f6f6f1';
const arrow='<span aria-hidden="true">↗</span>';
const brand=`<span class="lab-logo" aria-hidden="true"><i></i><i></i><i></i><i></i></span><strong>dtia<span>lab</span></strong>`;
document.querySelector('#app').innerHTML=`
<a class="skip-link" href="#main-content">Skip to content</a>
<header class="lab-header"><a class="lab-brand" href="/" aria-label="DTIA lab home">${brand}</a><div class="lab-name">Digital Twin Research Center<br>for Infrastructure Assets</div><button class="lab-menu-toggle" id="lab-menu-toggle" aria-expanded="false" aria-controls="lab-navigation">Menu <span>＋</span></button><nav id="lab-navigation" aria-label="Main navigation"><a href="#research">Research</a><a href="#showcases">Showcases</a><a href="#about">The lab</a><a class="nav-connect" href="#collaborate">Collaborate ${arrow}</a></nav></header>
<main id="main-content"><section class="lab-hero" aria-labelledby="hero-heading"><div class="hero-copy"><div class="lab-kicker"><span class="accent-square"></span> CONNECTING PHYSICAL & DIGITAL WORLDS</div><h1 id="hero-heading">Infrastructure.<br>Intelligence.<br><span>Impact.</span></h1><p>Understanding the systems we depend on.<br>Imagining what they could become.</p><a class="solid-link" href="#showcases">Explore our work ${arrow}</a><div class="hero-foot"><span>DTIA / RESEARCH THROUGH PROTOTYPING</span><a href="#about" aria-label="Read about DTIA">↓</a></div></div><div class="hero-art"><div class="hero-art-grid"></div><div class="visual-topline"><span>PHYSICAL SYSTEM → DIGITAL POSSIBILITY</span><span>01 / 02</span></div><div id="lab-visual" role="img" aria-label="Three-dimensional city research model with highlighted infrastructure landmarks"></div><div class="visual-coordinate coord-one">[ SYSTEMS ]<br>13.7563° N</div><div class="visual-coordinate coord-two">[ CONNECTIONS ]<br>100.5018° E</div><div class="visual-bottom"><div><span class="visual-cross">＋</span><small id="visual-status">CITY MODEL / LOADING GEOMETRY</small></div><button id="visual-motion" aria-pressed="true">Pause motion Ⅱ</button></div><span class="visual-caption">A schematic city, rendered from our working digital twin.</span></div></section>
<section class="lab-intro" id="about"><div class="section-index">01 — THE LAB</div><div><h2>A place to ask better questions<br>about the <em>built world.</em></h2><div class="intro-columns"><p>The Digital Twin Research Center for Infrastructure Assets (DTIA) brings physical infrastructure into a digital space where it can be explored, questioned, and understood.</p><p>Our ambition is to connect engineering, data, and design—turning observations into models, models into experiments, and experiments into more informed decisions.</p></div><a class="text-link" href="#research">Discover our research directions ${arrow}</a></div></section>
<section class="lab-research" id="research"><div class="section-head"><div><div class="section-index">02 — RESEARCH DIRECTIONS</div><h2>Across scales.<br>Between disciplines.</h2></div><p>From a single asset to an interconnected city, our research agenda follows the relationships that make infrastructure work.</p></div><div class="research-grid"><a href="#showcases" class="research-cell"><span class="research-number">R.01</span><div class="research-symbol symbol-sense" aria-hidden="true">⊙</div><h3>Observe &<br>represent</h3><p>Connect asset information and measurements to meaningful digital representations.</p><span class="research-tags">SENSING / DATA / GEOMETRY</span><span class="research-arrow">↗</span></a><a href="#showcases" class="research-cell"><span class="research-number">R.02</span><div class="research-symbol symbol-system" aria-hidden="true">⌗</div><h3>Model &<br>understand</h3><p>Explore how infrastructure behaves, and how individual assets relate to the wider system.</p><span class="research-tags">SYSTEMS / NETWORKS / ANALYTICS</span><span class="research-arrow">↗</span></a><a href="#showcases" class="research-cell"><span class="research-number">R.03</span><div class="research-symbol symbol-simulate" aria-hidden="true">⇄</div><h3>Simulate &<br>anticipate</h3><p>Test alternative conditions and examine the consequences before acting in the physical world.</p><span class="research-tags">SCENARIOS / RESILIENCE / ENERGY</span><span class="research-arrow">↗</span></a><a href="#showcases" class="research-cell"><span class="research-number">R.04</span><div class="research-symbol symbol-decide" aria-hidden="true">↗</div><h3>Interpret &<br>act</h3><p>Make complex system behavior legible through interactive tools for human judgment.</p><span class="research-tags">VISUALIZATION / INTERACTION / DESIGN</span><span class="research-arrow">↗</span></a></div></section>
<section class="lab-showcases" id="showcases"><div class="section-head"><div><div class="section-index">03 — WORKING DEMONSTRATORS</div><h2>Research you<br>can step inside.</h2></div><div class="showcase-intro"><p>Open the model. Change an assumption.<br>See a different possibility.</p><div class="showcase-filters" aria-label="Filter showcases"><button data-filter="all" aria-pressed="true">All work <small>02</small></button><button data-filter="energy" aria-pressed="false">Energy</button><button data-filter="cities" aria-pressed="false">Cities</button></div></div></div>
<article class="showcase showcase-energy" data-category="energy"><a class="showcase-image" href="/showcase/distribution" aria-label="Launch the distribution asset digital twin"><img src="/lab/distribution-showcase.png" alt="DTIA's working transformer network dashboard with asset readings and a three-dimensional coastal district" loading="eager" width="1440" height="960"><span class="image-corner">DTIA / 001</span><span class="image-launch">Explore live demo ${arrow}</span></a><div class="showcase-description"><div class="showcase-meta"><span>ENERGY SYSTEMS</span><span>INTERACTIVE PROTOTYPE</span></div><h3>Seeing the grid<br>as a living system.</h3><p>A distribution asset twin that connects transformer monitoring, fleet analytics, and power-quality experiments in one interactive environment.</p><ul><li>Inspect eight modeled transformers across two sample feeders</li><li>Explore EV demand, rooftop solar, and compensation scenarios</li><li>Compare electrical state, loading patterns, and review priorities</li></ul><div class="project-actions"><a class="solid-link" href="/showcase/distribution">Launch digital twin ${arrow}</a><button class="text-link" data-project="energy">Project notes +</button></div><small class="data-note">Synthetic telemetry · Illustrative network · Research demonstration</small></div></article>
<article class="showcase showcase-city" data-category="cities"><a class="showcase-image" href="/showcase/city" aria-label="Launch the Bangkok city digital twin"><img src="/lab/city-showcase.png" alt="Bangkok city digital twin showing its river, urban buildings, sample sensors, and environmental layers" loading="eager" width="1440" height="960"><span class="image-corner">DTIA / 002</span><span class="image-launch">Explore live demo ${arrow}</span></a><div class="showcase-description"><div class="showcase-meta"><span>URBAN SYSTEMS</span><span>INTERACTIVE PROTOTYPE</span></div><h3>A city.<br>Many possible futures.</h3><p>Explore Bangkok through a schematic urban twin. Move through the day and investigate the relationships between places, movement, and environmental conditions.</p><ul><li>Navigate a Blender-built city with four stylized landmarks</li><li>Inspect sample stations and their daily profiles</li><li>Explore traffic, air-quality zones, and an illustrative flood corridor</li></ul><div class="project-actions"><a class="solid-link" href="/showcase/city">Explore the city ${arrow}</a><button class="text-link" data-project="cities">Project notes +</button></div><small class="data-note">Schematic geometry · Simulated data · Not a forecast</small></div></article>
<div class="showcase-count" id="showcase-count" aria-live="polite">Showing 2 working demonstrators</div></section>
<section class="lab-method"><div class="section-index">04 — OUR APPROACH</div><div class="method-heading"><h2>Make the complex<br><span>tangible.</span></h2><p>A digital twin becomes useful when people can ask questions of it. Our approach places interactive experiments between a system and a decision.</p></div><ol class="method-steps"><li><span>01</span><h3>Represent</h3><p>Build a shared view of assets, their context, and their connections.</p></li><li><span>02</span><h3>Experiment</h3><p>Change assumptions, compare scenarios, and make limitations visible.</p></li><li><span>03</span><h3>Interpret</h3><p>Bring the results back to the engineering question that matters.</p></li></ol></section>
<section class="lab-collaborate" id="collaborate"><div class="section-index">05 — OPEN QUESTIONS, SHARED POSSIBILITIES</div><div><h2>What could we<br><em>understand together?</em></h2><p>Infrastructure challenges cross disciplines. The DTIA research agenda creates space for perspectives from engineering, computing, design, and the people who work with these systems.</p><a class="solid-link" href="https://github.com/nuiel9/bangkoktwin" target="_blank" rel="noopener">Explore the research code ${arrow}</a></div></section>
</main><footer class="lab-footer"><div class="footer-brand"><a class="lab-brand" href="/" aria-label="DTIA lab home">${brand}</a><p>Digital Twin Research Center<br>for Infrastructure Assets</p></div><div class="footer-links"><a href="#research">Research</a><a href="#showcases">Showcases</a><a href="#about">The lab</a><a href="https://github.com/nuiel9/bangkoktwin" target="_blank" rel="noopener">GitHub ↗</a></div><div class="footer-bottom"><span>DTIA · Exploring the possibilities of infrastructure.</span><span>All showcase data is simulated.</span><a href="#main-content">Back to top ↑</a></div></footer>
<dialog class="project-dialog" id="project-dialog"><button class="dialog-close" aria-label="Close project notes">×</button><div id="project-dialog-content"></div></dialog>`;

const menu=document.querySelector('#lab-menu-toggle');
const collaboration=document.querySelector('.lab-collaborate>div:last-child');
const contactLink=collaboration.querySelector('.solid-link');
contactLink.href='mailto:suwilai.ph@kmitl.ac.th?subject=DTIA%20research%20collaboration';
contactLink.removeAttribute('target');contactLink.removeAttribute('rel');
contactLink.innerHTML=`Start a conversation ${arrow}`;
contactLink.insertAdjacentHTML('afterend','<a class="collaboration-email" href="mailto:suwilai.ph@kmitl.ac.th">suwilai.ph@kmitl.ac.th</a>');
const nav=document.querySelector('#lab-navigation');
menu.onclick=()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open);};
nav.addEventListener('click',e=>{if(e.target.closest('a')){menu.setAttribute('aria-expanded','false');nav.classList.remove('is-open');}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.setAttribute('aria-expanded','false');nav.classList.remove('is-open');}});
document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{
  const filter=button.dataset.filter;
  document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));
  let count=0;document.querySelectorAll('[data-category]').forEach(card=>{card.hidden=filter!=='all'&&card.dataset.category!==filter;if(!card.hidden)count++;});
  document.querySelector('#showcase-count').textContent=`Showing ${count} working demonstrator${count===1?'':'s'}`;
});
const notes={energy:{title:'Distribution asset digital twin',category:'ENERGY SYSTEMS / DTIA 001',question:'How can an interactive asset model make distribution-system behavior easier to inspect?',body:'This demonstrator brings a schematic coastal district together with eight synthetic transformer assets, daily electrical profiles, and feeder-level analytics. The monitoring, analysis, and optimization views share one deterministic simulation model.',limitations:'EV, solar, and compensation responses are illustrative assumptions. Asset geometry is not surveyed GIS, and the simulation is not a validated power-flow solver. Offline telemetry indicates unknown state, not a confirmed outage.',url:'/showcase/distribution'},cities:{title:'Bangkok city digital twin',category:'URBAN SYSTEMS / DTIA 002',question:'How can a shared urban model help people explore places and changing conditions?',body:'A procedural Blender city is connected to selectable sample stations, a time-of-day simulation, and environmental layers. Users can move between four stylized landmarks, inspect generated readings, and export snapshots.',limitations:'Geometry and station positions are schematic. Traffic and environmental readings are generated. The flood corridor is a visual scenario, not a hydrological prediction.',url:'/showcase/city'}};
const dialog=document.querySelector('#project-dialog');
document.querySelectorAll('[data-project]').forEach(button=>button.onclick=()=>{const n=notes[button.dataset.project];document.querySelector('#project-dialog-content').innerHTML=`<div class="lab-kicker">${n.category}</div><h2>${n.title}</h2><h3>${n.question}</h3><p>${n.body}</p><h4>Scope of the prototype</h4><p>${n.limitations}</p><a class="solid-link" href="${n.url}">Open the demonstrator ${arrow}</a>`;dialog.showModal();});
document.querySelector('.dialog-close').onclick=()=>dialog.close();
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
import('./lab-visual').then(({mountLabVisual})=>mountLabVisual(document.querySelector('#lab-visual'))).catch(()=>{document.querySelector('#visual-status').textContent='EXPLORE THE WORKING CITY MODEL BELOW';document.querySelector('#visual-motion').hidden=true;document.querySelector('.hero-art').classList.add('visual-fallback');});
